// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgZD0OvauNYeWS9NiuTzpRIUGR86SkxXM',
    appId: '1:238339267074:web:133de1007904b89642e51b',
    messagingSenderId: '238339267074',
    projectId: 'adaptive-planner-cd88b',
    authDomain: 'adaptive-planner-cd88b.firebaseapp.com',
    storageBucket: 'adaptive-planner-cd88b.firebasestorage.app',
    measurementId: 'G-N8RBW2D0KE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGKyDzdDMtes43YvaE0ihON7B8hurr4Mo',
    appId: '1:238339267074:android:3c0fe87a0c1f882742e51b',
    messagingSenderId: '238339267074',
    projectId: 'adaptive-planner-cd88b',
    storageBucket: 'adaptive-planner-cd88b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI2uWnWLU38G0PXdPSa2ceChfs24iOA9g',
    appId: '1:238339267074:ios:0bbdad33b3e4209142e51b',
    messagingSenderId: '238339267074',
    projectId: 'adaptive-planner-cd88b',
    storageBucket: 'adaptive-planner-cd88b.firebasestorage.app',
    iosBundleId: 'com.example.adaptivePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI2uWnWLU38G0PXdPSa2ceChfs24iOA9g',
    appId: '1:238339267074:ios:0bbdad33b3e4209142e51b',
    messagingSenderId: '238339267074',
    projectId: 'adaptive-planner-cd88b',
    storageBucket: 'adaptive-planner-cd88b.firebasestorage.app',
    iosBundleId: 'com.example.adaptivePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgZD0OvauNYeWS9NiuTzpRIUGR86SkxXM',
    appId: '1:238339267074:web:9fdbbbf7ee7aca9542e51b',
    messagingSenderId: '238339267074',
    projectId: 'adaptive-planner-cd88b',
    authDomain: 'adaptive-planner-cd88b.firebaseapp.com',
    storageBucket: 'adaptive-planner-cd88b.firebasestorage.app',
    measurementId: 'G-3VLQPV1VLZ',
  );
}
